config/routes.rb
Lunch::Application.routes.draw do
  get "admin/index"
  devise_for :users
  get "users" => 'users#index'
  resources :carts
  resources :menus
  resources :orders
  resources :line_items, only: [:create]

  root 'infos#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  has_many :line_items 

  def add_menu_item(menu_id)
    current_item = line_items.build(menu_id: menu_id)
  end

  def total_price
    line_items.to_a.sum {|item| item.menu.price }
  end

  def check_category
    counter = 0
    temp = []
    line_items.to_a.each {|item| 
      temp[counter] = item.menu.category_id 
      counter += 1 
    }
    if ((temp[0] === temp[1] ) || (temp[0] === temp[2]) || (temp[1] === temp[2]) || (line_items.count > 3))
      return false
    else
      return true
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :menus

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :menu
  belongs_to :cart
  belongs_to :order
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  
  belongs_to :category
  has_many :line_items
  has_many :orders, through: :line_items  

  validates_presence_of :title, :price, :description, :published_on
  validates :title, length: { in: 3..50}, uniqueness: true
  validates :description, length: { maximum: 500 }

  def self.filter(category_id)
    where('menus.category_id= ?', category_id)
  end

  def self.time_ago(count)
    count_int = count.to_i
    date = Date.parse(count_int.days.ago.to_s)
    if count.to_i < 6
      where(created_at: date..date.end_of_day)
    else
      where('created_at >= ?', 6.days.ago)
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :line_items

  validates_presence_of :name, :price, :address, :email
  validates :name, length: { in: 3..50}
  validates :address, length: {minimum:10, maximum: 50}

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def self.total_price
    self.sum {|item| item.price }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    admin
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  helper_method :categories


  def categories
    @categories = Category.all
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  def current_cart
    cart = Cart.where(id: session[:cart_id]).first_or_create
    session[:cart_id] = cart.id
    cart
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 
  before_action :find_cart, only: [ :show, :destroy, :update, :edit]
  

  def index
    @carts = Cart.all
  end

  def show
  end  

  def new
    @cart = Cart.new
  end

  def create
    @cart = Cart.new(params[:cart])
    if @cart.save
      redirect_to carts_path
    end
  end

  def update
    if @cart.update_attributes(params[:cart])
      redirect_to @cart
    end
  end

  private
  def find_cart
    @cart = Cart.find(params[:id])
  end

end

app/controllers/infos_controller.rb
class InfosController < ApplicationController

  def index
    if params[:filter]
      @menus = Menu.filter(params[:filter]).order("Created_at DESC")
    elsif params[:time_ago]
      @menus = Menu.time_ago(params[:time_ago]);
    else
      @menus = Menu.order("Created_at DESC").limit(5);
    end
    @cart = current_cart
    @menusall = Menu.all
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  def create
    @cart = current_cart
    menu = Menu.find(params[:menu_id])
    @line_item = @cart.add_menu_item(menu.id)
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to root_path }
        format.js 
      end
    end
  end


end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
 
  before_action :current_admin
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @menus = Menu.all
    respond_with(@menus)
  end

  def show
    respond_with(@menu)
  end

  def new
    @menu = Menu.new
    respond_with(@menu)
  end

  def edit
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.save
    respond_with(@menu)
  end

  def update
    @menu.update(menu_params)
    respond_with(@menu)
  end

  def destroy
    @menu.destroy
    respond_with(@menu)
  end

  private

  def current_admin
    if !current_user.admin?
      redirect_to root_path, notice: "You are not admin!"
    end
  end

  def set_menu
    @menu = Menu.find(params[:id])
  end

  def menu_params
    params.require(:menu).permit(:title, :category_id, :image_url, :description, :price)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

before_action :current_admin, only: [:index, :show, :edit, :update, :destroy]

def index
  @orders = Order.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
end

def create
  @cart = current_cart
  @order = Order.new(order_params)
  @order.add_line_items_from_cart(current_cart)
  @order.price = @cart.total_price
    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
      redirect_to root_path, notice: 'Thank you for your order.'
    else
      @cart = current_cart
      render action: "new" 
    end
end

def new
  @cart = current_cart
  if @cart.line_items.empty?
  redirect_to root_path, notice: "Your cart is empty"
  return
  end
  if !(@cart.check_category)
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    redirect_to root_path, notice: "You must pay 1 - first, 1 - main, 1 - drink"
  return
  end 
  @order = Order.new
  respond_to do |format|
    format.html
  end
end

 private

  def current_admin
    if !current_user.admin?
      redirect_to root_path, notice: "You are not admin!"
    end
  end

 def find_order
   @order = Order.find(params[:id])
 end

 def order_params
   params.require(:order).permit(:name, :address, :email, :price)
 end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @users = User.all
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart.html.erb
<h4>Your Lunch</h4>
  <table>
    <%= render(cart.line_items) %>
    <tr>
      
    </tr>
  </table>
  <h5>Total</h5>
  <b><%= number_to_currency(cart.total_price) %></b>
  <div>
     <%= button_to "Checkout", new_order_path, method: :get, :class => 'btn btn-success' %>
  </div>

app/views/carts/show.html.erb
<div class="cartt">
  <%= render @cart %>
</div>

app/views/line_items/_line_item.html.erb
  <tr>
    <td><%= line_item.menu.title %></td>
    <td><%= number_to_currency(line_item.menu.price) %></td>
  </tr>

app/views/line_items/create.js.erb
$('.cart').html("<%= j render @cart %>");

app/views/menus/_form.html.erb
<%= form_for @menu, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :published_on, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :published_on, :class => 'publishedokey' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :category_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                menus_path, :class => 'btn' %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<%- model_class = Menu -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/menus/index.html.erb
<%- model_class = Menu -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:image_url) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= link_to menu.id, menu_path(menu) %></td>
        <td><%= menu.title %></td>
        <td><%= menu.category_id %></td>
        <td><%= menu.image_url %></td>
        <td><%= menu.description %></td>
        <td><%= menu.price %></td>
        <td><%=l menu.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_menu_path(menu), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      menu_path(menu),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_menu_path,
            :class => 'btn btn-primary' %>

app/views/menus/new.html.erb
<%- model_class = Menu -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/menus/show.html.erb
<%- model_class = Menu -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @menu.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @menu.category_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_url) %>:</strong></dt>
  <dd><%= @menu.image_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @menu.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @menu.price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              menus_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_menu_path(@menu), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              menu_path(@menu),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/orders/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@order.errors.count, "error") %> prohibited this rorde from being saved:</h2>
      <ul>  
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br /> 
    <%= f.text_field :name,size: 40 %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address,size: 40, rows: 3,cols: 38 %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email,size: 40 %>
  </div>
  <div class="actions">
    <%= f.submit 'Place Order' %><br />
  </div>

<% end %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
      <th>Name<th>
      <th>Address</th>
      <th>Email</th>
      <th>Price</th>
      <th>Created_at</th>
      <th class="offset">Destroy</th>

  </tr>

<% @orders.each do |order| %>
  <tr class="offset">
    <td><%= order.name %></td>
    <td></td>
    <td><%= order.address %></td>
    <td><%= order.email %></td>
    <td><%= order.price %></td>
    <td><%= order.created_at %></td>
    <td><%= link_to 'Destroy',order, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Order', new_order_path %>
<p><%= will_paginate @orders %></p>

app/views/orders/new.html.erb
  <div>
    <fieldset>
      <legend>Please Enter Details</legend>
      <%= render 'form' %>
    </fieldset>
  </div>