config/routes.rb
Lunch::Application.routes.draw do
  get "admin/index"
  devise_for :users
  get "users" => 'users#index'
  resources :carts
  resources :menus
  resources :orders
  resources :line_items, only: [:create]

  root 'infos#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  has_many :line_items 

  def add_menu_item(menu_id)
    current_item = line_items.build(menu_id: menu_id)
  end

  def total_price
    line_items.to_a.sum {|item| item.menu.price }
  end

  def check_category
    counter = 0
    temp = []
    line_items.to_a.each {|item| 
      temp[counter] = item.menu.category_id 
      counter += 1 
    }
    if ((temp[0] === temp[1] ) || (temp[0] === temp[2]) || (temp[1] === temp[2]) || (line_items.count > 3))
      return false
    else
      return true
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :menus

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :menu
  belongs_to :cart
  belongs_to :order
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  
  belongs_to :category
  has_many :line_items
  has_many :orders, through: :line_items  

  validates_presence_of :title, :price, :description, :published_on
  validates :title, length: { in: 3..50}, uniqueness: true
  validates :description, length: { maximum: 500 }

  def self.filter(category_id)
    where('menus.category_id= ?', category_id)
  end

  def self.time_ago(count)
    count_int = count.to_i
    date = Date.parse(count_int.days.ago.to_s)
    if count.to_i < 6
      where(created_at: date..date.end_of_day)
    else
      where('created_at >= ?', 6.days.ago)
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :line_items

  validates_presence_of :name, :price, :address, :email
  validates :name, length: { in: 3..50}
  validates :address, length: {minimum:10, maximum: 50}

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def self.total_price
    self.sum {|item| item.price }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    admin
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 
  before_action :find_cart, only: [ :show, :destroy, :update, :edit]
  

  def index
    @carts = Cart.all
  end

  def show
  end  

  def new
    @cart = Cart.new
  end

  def create
    @cart = Cart.new(params[:cart])
    if @cart.save
      redirect_to carts_path
    end
  end

  def update
    if @cart.update_attributes(params[:cart])
      redirect_to @cart
    end
  end

  private
  def find_cart
    @cart = Cart.find(params[:id])
  end

end

app/controllers/infos_controller.rb
class InfosController < ApplicationController

  def index
    if params[:filter]
      @menus = Menu.filter(params[:filter]).order("Created_at DESC")
    elsif params[:time_ago]
      @menus = Menu.time_ago(params[:time_ago]);
    else
      @menus = Menu.order("Created_at DESC").limit(5);
    end
    @cart = current_cart
    @menusall = Menu.all
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
 
  before_action :current_admin
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @menus = Menu.all
    respond_with(@menus)
  end

  def show
    respond_with(@menu)
  end

  def new
    @menu = Menu.new
    respond_with(@menu)
  end

  def edit
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.save
    respond_with(@menu)
  end

  def update
    @menu.update(menu_params)
    respond_with(@menu)
  end

  def destroy
    @menu.destroy
    respond_with(@menu)
  end

  private

  def current_admin
    if !current_user.admin?
      redirect_to root_path, notice: "You are not admin!"
    end
  end

  def set_menu
    @menu = Menu.find(params[:id])
  end

  def menu_params
    params.require(:menu).permit(:title, :category_id, :image_url, :description, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @users = User.all
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lunch" %></title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
           
          <div class="container nav-collapse">
            <ul class="nav">
	       <li><%= link_to "Home", root_path  %></li>
	       <% if current_user %>
		 <% if current_user.admin? %>
                   <li><%= link_to "Orders", orders_path  %></li>
                   <li><%= link_to "Users", users_path  %></li>
		   <li><%= link_to "Add Items", menus_path  %></li>
	         <% end %>
	       <% end %>
	        
		<% if user_signed_in? %>
		  <li>
		    <%= link_to("Logout" ,destroy_user_session_path, method: :delete) %>
		  </li>
		  <li><%= link_to "Account", edit_user_registration_path  %></li>
		  <li class="loginn">
		    Logged in as <%= current_user.username %>
		  </li>
		<% else %>
		  <li>
		    <%= link_to("Login", new_user_session_path) %>
		  </li>
		<% end %>


            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span2">
            <% if @cart %>
              <div class="cart">
                <%= render @cart %>
	      </div>
            <% end %>
          </div>
          <div class="span8">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span2">
            <div class="well sidebar-nav">
              <h3>3 Steps</h3>
              <ul class="nav nav-list">
                <li class="nav-header">for order</li>
                <% categories.each do |category| %>
                  <li class='reload'><%= link_to category.name, root_path(filter: category.id) %></li>
                <% end %>	
              </ul>	     
	      <h4>Weekdays</h4>
 	      <ul class="nav nav-list">
		<li class='reload'><%= link_to 2.days.ago.to_time.strftime('%B %e'), root_path(time_ago: 2) %></li>
		<li class='reload'><%= link_to 3.days.ago.to_time.strftime('%B %e'), root_path(time_ago: 3) %></li>
		<li class='reload'><%= link_to 4.days.ago.to_time.strftime('%B %e'), root_path(time_ago: 4) %></li>
		<li class='reload'><%= link_to 5.days.ago.to_time.strftime('%B %e'), root_path(time_ago: 5) %></li>
	        <li class='reload'><%= link_to "More than 5 days", root_path(time_ago: 6) %></li>
	      </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>